USE mydb;

INSERT INTO movies
VALUES
(299537, "Captain Marvel", "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.", "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg", "2019-03-06", 124, "en"),
(166428, "How to Train Your Dragon: The Hidden World", "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.", "/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg", "2019-01-03", 104, "en"),
(458723, "Us", "Husband and wife Gabe and Adelaide Wilson take their kids to their beach house expecting to unplug and unwind with friends. But as night descends, their serenity turns to tension and chaos when some shocking visitors arrive uninvited.", "/ux2dU1jQ2ACIMShzB3yP93Udpzc.jpg", "2019-03-14", 116, "en"),
(424783, "Bumblebee", "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.  When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.", "/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg", "2018-12-15", 114, "en"),
(504172, "The Mule", "Earl Stone, a man in his 80s who is broke, alone, and facing foreclosure of his business when he is offered a job that simply requires him to drive. Easy enough, but, unbeknownst to Earl, he’s just signed on as a drug courier for a Mexican cartel. He does so well that his cargo increases exponentially, and Earl hit the radar of hard-charging DEA agent Colin Bates.", "/oeZh7yEz3PMnZLgBPhrafFHRbVz.jpg", "2018-12-14", 116, "en"),
(299536, "Avengers: Infinity War", "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.", "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg", "2018-04-25", 149, "en"),
(450001, "Master Z: Ip Man Legacy", "After being defeated by Ip Man, Cheung Tin Chi is attempting to keep a low profile. While going about his business, he gets into a fight with a foreigner by the name of Davidson, who is a big boss behind the bar district. Tin Chi fights hard with Wing Chun and earns respect.", "/2WfjB6FUDTIBVI2y02UGbnHR82s.jpg", "2018-12-20", 107, "cn"),
(390634, "Fate/stay night: Heaven’s Feel II. lost butterfly", "Theatrical-release adaptation of the visual novel \"Fate/stay night\", following the third and final route. (Part 2 of a trilogy.)", "/4tS0iyKQBDFqVpVcH21MSJwXZdq.jpg", "2019-01-12", 120, "ja"),
(297802, "Aquaman", "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.", "/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg", "2018-12-07", 144, "en"),
(324857, "Spider-Man: Into the Spider-Verse", "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.", "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg", "2018-12-07", 117, "en");

